name = "urbanexposed"
main = "src/index.js"
compatibility_date = "2024-05-01"
compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
binding = "CDN"
bucket_name = "urbanexposed-cdn"

[[d1_databases]]
binding = "DATABASE"
database_name = "urbanexposed-db"
database_id = "35f9dd21-1444-4b06-b660-f739469d430c"

[vars]
MAX_IMAGE_SIZE = "10485760"
MAX_VIDEO_SIZE = "52428800"