name = "urbanexposed"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[r2_buckets]]
binding = "CDN"
bucket_name = "urbanexposed-cdn"

[[d1_databases]]
binding = "DATABASE"
database_name = "urbanexposed-db"
database_id = "35f9dd21-1444-4b06-b660-f739469d430c"